repo:
  url: https://github.com/Vincent777/InfiniLM.git
  branch: main

github:
  status_context_prefix: "ci/infinilm"

platforms:
  moore:
    image:
      dockerfile: images/moore/
      build_args:
        BASE_IMAGE: sh-harbor.mthreads.com/mcctest/vllm_musa:20251112_hygon
        APT_MIRROR: https://mirrors.tuna.tsinghua.edu.cn/ubuntu
        PIP_INDEX_URL: https://pypi.org/simple
        InfiniCore_BRANCH: musa_silu_and_mul
    docker_args:
      - "--user=root"
      - "--network=host"
      - "--privileged"
      - "--cap-add=ALL"
      - "--pid=host"
      - "--ipc=host"
      - "--workdir=/workspace"
    volumes:
      - /data:/data
      - /data-aisoft:/data-aisoft
      - /data-aisoft/artifacts/CI_moore_test/__WORKSPACE__:/artifacts
    setup: pip install .[dev] --no-build-isolation
    jobs:
      gpu_inferencetest:
          type: inferencetest
          resources:
            ngpus: [1, 4]
            gpu_style: nvidia
            shm_size: 64g
            timeout: 3600
          stages:
            - name: test
              run: python InfiniLM/examples/test_infer.py --device nvidia --model=/data-aisoft/mechdancer/models/9g_8b_thinking_llama/
      gpu_benchtest:
        type: benchtest
        resources:
          gpu_style: nvidia
          shm_size: 64g
          timeout: 3600
        env:
          TEST_PARAM: ['default', '--enable-paged-attn', '--enable-paged-attn --enable-graph']
        stages:
          - name: test
            run: python InfiniLM/examples/bench.py --device nvidia --model=/data-aisoft/mechdancer/models/9g_8b_thinking_llama/ --input-len=256,1024 --output-len=256,1024 --batch-size=8 <TEST_PARAM>
      gpu_accuracytest:
        type: accuracytest
        resources:
          gpu_style: nvidia
          shm_size: 64g
          timeout: 3600
        env:
          TEST_PARAM: ['default', '--enable-paged-attn --enable-graph']
        stages:
          - name: test
            run: python InfiniLM/test/bench/test_benchmark.py --device nvidia --model /data-aisoft/mechdancer/models/9g_8b_thinking_llama/ --bench mmlu --backend cpp --max-new-tokens 5 --cache-dir /data-aisoft/pepe/datasets/ --split=val <TEST_PARAM>
      gpu_servicetest:
        type: servicetest
        resources:
          gpu_style: nvidia
          shm_size: 64g
          timeout: 3600
        env:
          MODEL_LIST: 9g_8b_thinking_llama
          ENGINE: InfiniLM
          TEST_PARAM: ['default', '--enable-paged-attn --cache-type=paged', '--enable-paged-attn --cache-type=paged --enable-graph']
        stages:
          - name: test
            run: python InfiniLM/scripts/test_perf.py --verbose
