repo:
  url: https://github.com/Vincent777/InfiniLM.git
  branch: main

github:
  status_context_prefix: "ci/infinilm"

platforms:
  moore:
    image:
      dockerfile: images/moore/
      build_args:
        BASE_IMAGE: sh-harbor.mthreads.com/mcctest/vllm_musa:20251112_hygon
        APT_MIRROR: https://mirrors.tuna.tsinghua.edu.cn/ubuntu
        PIP_INDEX_URL: https://pypi.org/simple
        InfiniCore_BRANCH: musa_silu_and_mul
    docker_args:
      - "--user=root"
      - "--network=host"
      - "--privileged"
      - "--cap-add=ALL"
      - "--pid=host"
      - "--ipc=host"
      - "--workdir=/workspace"
    volumes:
      - /data:/data
      - /data-aisoft:/data-aisoft
      - /data-aisoft/artifacts/CI_moore_test/__WORKSPACE__:/artifacts
    setup: pip install .[dev] --no-build-isolation
    jobs:
      gpu_inferencetest:
          type: inferencetest
          resources:
            ngpus: [1, 4]
            gpu_style: none
            shm_size: 64g
            timeout: 3600
          stages:
            - name: test
              run: python InfiniLM/examples/test_infer.py --device moore --model=/data-aisoft/mechdancer/models/9g_8b_thinking_llama/
      gpu_benchtest:
        type: benchtest
        resources:
          gpu_style: none
          shm_size: 64g
          timeout: 3600
        env:
          TEST_PARAM: ['batch-size=1', '--enable-paged-attn batch-size=1', '--enable-paged-attn --enable-graph batch-size=8']
        stages:
          - name: test
            run: python InfiniLM/examples/bench.py --device moore --model=/data-aisoft/mechdancer/models/9g_8b_thinking_llama/ --input-len=256,1024 --output-len=256,1024 <TEST_PARAM>
      gpu_accuracytest:
        type: accuracytest
        resources:
          gpu_style: none
          shm_size: 64g
          timeout: 3600
        env:
          TEST_PARAM: ['--bench ceval', '--bench mmlu']
        stages:
          - name: test
            run: python InfiniLM/test/bench/test_benchmark.py --moore /data-aisoft/zhushuang/models/9g_8b_thinking_llama/ --subject all --backend cpp --ndev 1 --output_csv 8b_mmlu_paged_results.csv --split val --cache_dir /data-aisoft/pepe/datasets/ <TEST_PARAM>
      gpu_servicetest:
        type: servicetest
        resources:
          gpu_style: none
          shm_size: 64g
          timeout: 3600
        env:
          MODEL_LIST: 9g_8b_thinking_llama
          ENGINE: InfiniLM
          TEST_PARAM: ['--cache_type=static', '--cache_type=paged --num_blocks=512 --block_size=64', '--cache_type=paged --enable-graph --num_blocks=512 --block_size=64']
        stages:
          - name: test
            run: python InfiniLM/scripts/test_perf.py --verbose
