name: Clang Format
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "21"
          include-regex: '^.*\.(h|cc|cuh|mlu)$'
